// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQmZxwbUm5vWMIbTO3yHoTqyycAUTN_co',
    appId: '1:64477076913:web:c78f0fd481e6ff8236f190',
    messagingSenderId: '64477076913',
    projectId: 'glint-1990',
    authDomain: 'glint-1990.firebaseapp.com',
    storageBucket: 'glint-1990.firebasestorage.app',
    measurementId: 'G-KYZ042D2Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp0l5OJ4UxziMnDgo5E-NoCFJlmIggLzU',
    appId: '1:64477076913:android:b4390480d80ffd4d36f190',
    messagingSenderId: '64477076913',
    projectId: 'glint-1990',
    storageBucket: 'glint-1990.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA72PpOHsN-5x_VBem6hx07GiU-4apfF78',
    appId: '1:64477076913:ios:54abd3e4b2b0ded936f190',
    messagingSenderId: '64477076913',
    projectId: 'glint-1990',
    storageBucket: 'glint-1990.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA72PpOHsN-5x_VBem6hx07GiU-4apfF78',
    appId: '1:64477076913:ios:54abd3e4b2b0ded936f190',
    messagingSenderId: '64477076913',
    projectId: 'glint-1990',
    storageBucket: 'glint-1990.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQmZxwbUm5vWMIbTO3yHoTqyycAUTN_co',
    appId: '1:64477076913:web:28c648dbebf9b32936f190',
    messagingSenderId: '64477076913',
    projectId: 'glint-1990',
    authDomain: 'glint-1990.firebaseapp.com',
    storageBucket: 'glint-1990.firebasestorage.app',
    measurementId: 'G-DK8GF2TM6F',
  );
}
