name: travel_app
description: A cross-platform travel app with vibrant UI.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  cloud_firestore: ^5.4.3
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.6
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/placeholder.png 